version: '3.1'
services:
  db:
    image: postgres
    container_name: castpet-postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: milad
      POSTGRES_USER: postgres
      POSTGRES_DB: castpet-dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db: {}
